[package]
edition = "2024"
name = "Creek"
version = "0.0.1"


[dependencies]
coin_gr = { local = "../coins/coin_gr" }
coin_gy = { local = "../coins/coin_gy" }
coin_gusd = { local = "../coins/coin_gusd" }
TestCoin = { local = "../../contracts_other/test_coin" }
Math = { local = "../libs/math" }
X = { local = "../libs/x" }
CoinDecimalsRegistry = { local = "../libs/coin_decimals_registry" }
XOracle = { local = "../sui_x_oracle/x_oracle" }

[addresses]
protocol = "0x0"