[package]
edition = "2024"
name = "ScallopProtocol"
version = "0.0.1"
published-at = "0x83bbe0b3985c5e3857803e2678899b03f3c4a31be75006ab03faf268c014ce41"


[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"

[dependencies]
coin_xaum = { local = "../coin_xaum" }
global_config = { local = "../global_config" }
coin_gr = { local = "../coin_gr" }
coin_gy = { local = "../coin_gy" }

[dependencies.Math]
local = "../libs/math"

[dependencies.X]
local = "../libs/x"

[dependencies.Whitelist]
local = "../libs/whitelist"

[dependencies.CoinDecimalsRegistry]
local = "../libs/coin_decimals_registry"

[dependencies.XOracle]
local = "../sui_x_oracle/x_oracle"

[addresses]
protocol = "0xefe8b36d5b2e43728cc323298626b83177803521d195cfb11e15b910e892fddf"

coin_xaum = "0x56ced0870e2274f24a447640fcf08f37b5b4e9f8113b56f78801312392b1061c"
global_config = "0x63bf5a22e224a42d1c407e9c898299828acec8def26a0a947e69b3d5bdfa1cf5"
coin_gr = "0xf3a8bbe23733473b1797fb79e710ad73943983e3c6a39730ff187b3214050ff9"
coin_gy = "0x24bfd23b897cd01a1eedb965f5b6ca72fcc66dcfd2249d26a7d1caac67bac7a5" 