[package]
name = "SupraRule"
version = "0.0.1"
edition = "2024"

[dependencies]
SupraOracle = { git = "https://github.com/Entropy-Foundation/dora-interface", subdir = "sui/testnet/supra_holder", rev = "testnet" }
XOracle = {local = "../x_oracle"}


[addresses]
supra_rule = "0x0"
