[package]
name = "SwitchboardOnDemandRule"
version = "0.0.1"
edition = "2024"

[dependencies]
Switchboard = {git = "https://github.com/switchboard-xyz/sui.git", subdir = "on_demand", rev = "testnet"}
XOracle = {local = "../x_oracle"}

[addresses]
switchboard_on_demand_rule = "0x0"
